import './globals.css'
import Navbar from "../components/Navbar";
import { Inter } from "next/font/google"

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  themeColor: "#B6E3C5"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-background'>
      <body className="bg-background">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
